---

- name: install prometheus-node-exporter
  package:
    name: prometheus-node-exporter
    state: present

- name: start prometheus-node-exporter
  systemd:
    name: prometheus-node-exporter
    enabled: yes
    state: started
